
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGraphicsDropShadowEffect


class Edit_patient_details(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1003, 400)
        MainWindow.setStyleSheet("#centralwidget {\n"
"border:none;\n"
"border-radius:25px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"background:#ffffff;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.widget.setFont(font)
        self.widget.setStyleSheet("color:#4169E1")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.date_txtlabel = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.date_txtlabel.setFont(font)
        self.date_txtlabel.setStyleSheet("color:#4169E1")
        self.date_txtlabel.setObjectName("date_txtlabel")
        self.horizontalLayout_6.addWidget(self.date_txtlabel)
        self.gridLayout.addWidget(self.widget_3, 2, 1, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.tim_txtlabel = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tim_txtlabel.setFont(font)
        self.tim_txtlabel.setObjectName("tim_txtlabel")
        self.horizontalLayout_5.addWidget(self.tim_txtlabel)
        self.gridLayout.addWidget(self.widget_4, 2, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.widget)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.gender_options = QtWidgets.QComboBox(self.widget_8)
        self.gender_options.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gender_options.setFont(font)
        self.gender_options.setStyleSheet("border:none")
        self.gender_options.setObjectName("gender_options")
        self.gender_options.addItem("")
        self.gender_options.addItem("")
        self.gender_options.addItem("")
        self.horizontalLayout_4.addWidget(self.gender_options)
        self.gridLayout.addWidget(self.widget_8, 1, 2, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widget_6.setFont(font)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.id_txtlabel = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.id_txtlabel.setFont(font)
        self.id_txtlabel.setObjectName("id_txtlabel")
        self.horizontalLayout.addWidget(self.id_txtlabel)
        self.gridLayout.addWidget(self.widget_6, 0, 0, 1, 2)
        self.widget_7 = QtWidgets.QWidget(self.widget)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.weight_txtlael = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.weight_txtlael.setFont(font)
        self.weight_txtlael.setObjectName("weight_txtlael")
        self.horizontalLayout_3.addWidget(self.weight_txtlael)
        self.gridLayout.addWidget(self.widget_7, 1, 1, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.widget_5.setFont(font)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.name_lineEdit = QtWidgets.QLineEdit(self.widget_5)
        self.name_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.name_lineEdit.setStyleSheet("border-radius:15px;\n"
"border: 1px solid #4169e1")
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.horizontalLayout_2.addWidget(self.name_lineEdit)
        self.gridLayout.addWidget(self.widget_5, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.widget_2.setFont(font)
        self.widget_2.setStyleSheet("background:#ffffff;\n"
"border:none\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setSpacing(9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.k_key = QtWidgets.QPushButton(self.widget_2)
        self.k_key.setMinimumSize(QtCore.QSize(35, 35))
        self.k_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.k_key.setFont(font)
        self.k_key.setObjectName("k_key")
        self.gridLayout_2.addWidget(self.k_key, 1, 20, 1, 3)
        self.t_key = QtWidgets.QPushButton(self.widget_2)
        self.t_key.setMinimumSize(QtCore.QSize(35, 35))
        self.t_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.t_key.setFont(font)
        self.t_key.setObjectName("t_key")
        self.gridLayout_2.addWidget(self.t_key, 0, 11, 1, 2, QtCore.Qt.AlignLeft)
        self.o_key = QtWidgets.QPushButton(self.widget_2)
        self.o_key.setMinimumSize(QtCore.QSize(35, 35))
        self.o_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.o_key.setFont(font)
        self.o_key.setObjectName("o_key")
        self.gridLayout_2.addWidget(self.o_key, 0, 19, 1, 3)
        self.m_key = QtWidgets.QPushButton(self.widget_2)
        self.m_key.setMinimumSize(QtCore.QSize(35, 35))
        self.m_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.m_key.setFont(font)
        self.m_key.setObjectName("m_key")
        self.gridLayout_2.addWidget(self.m_key, 2, 18, 1, 3)
        self.j_key = QtWidgets.QPushButton(self.widget_2)
        self.j_key.setMinimumSize(QtCore.QSize(35, 35))
        self.j_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.j_key.setFont(font)
        self.j_key.setObjectName("j_key")
        self.gridLayout_2.addWidget(self.j_key, 1, 17, 1, 3)
        self.h_key = QtWidgets.QPushButton(self.widget_2)
        self.h_key.setMinimumSize(QtCore.QSize(35, 35))
        self.h_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.h_key.setFont(font)
        self.h_key.setObjectName("h_key")
        self.gridLayout_2.addWidget(self.h_key, 1, 15, 1, 2)
        self.s_key = QtWidgets.QPushButton(self.widget_2)
        self.s_key.setMinimumSize(QtCore.QSize(35, 35))
        self.s_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s_key.setFont(font)
        self.s_key.setObjectName("s_key")
        self.gridLayout_2.addWidget(self.s_key, 1, 4, 1, 3, QtCore.Qt.AlignHCenter)
        self.f_key = QtWidgets.QPushButton(self.widget_2)
        self.f_key.setMinimumSize(QtCore.QSize(35, 35))
        self.f_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.f_key.setFont(font)
        self.f_key.setObjectName("f_key")
        self.gridLayout_2.addWidget(self.f_key, 1, 10, 1, 3, QtCore.Qt.AlignHCenter)
        self.I_key = QtWidgets.QPushButton(self.widget_2)
        self.I_key.setMinimumSize(QtCore.QSize(35, 35))
        self.I_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.I_key.setFont(font)
        self.I_key.setObjectName("I_key")
        self.gridLayout_2.addWidget(self.I_key, 0, 17, 1, 2)
        self.e_key = QtWidgets.QPushButton(self.widget_2)
        self.e_key.setMinimumSize(QtCore.QSize(35, 35))
        self.e_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.e_key.setFont(font)
        self.e_key.setObjectName("e_key")
        self.gridLayout_2.addWidget(self.e_key, 0, 5, 1, 3)
        self.w_key = QtWidgets.QPushButton(self.widget_2)
        self.w_key.setMinimumSize(QtCore.QSize(35, 35))
        self.w_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.w_key.setFont(font)
        self.w_key.setObjectName("w_key")
        self.gridLayout_2.addWidget(self.w_key, 0, 2, 1, 3)
        self.z_key = QtWidgets.QPushButton(self.widget_2)
        self.z_key.setMinimumSize(QtCore.QSize(35, 35))
        self.z_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.z_key.setFont(font)
        self.z_key.setObjectName("z_key")
        self.gridLayout_2.addWidget(self.z_key, 2, 3, 1, 3, QtCore.Qt.AlignHCenter)
        self.d_key = QtWidgets.QPushButton(self.widget_2)
        self.d_key.setMinimumSize(QtCore.QSize(35, 35))
        self.d_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.d_key.setFont(font)
        self.d_key.setObjectName("d_key")
        self.gridLayout_2.addWidget(self.d_key, 1, 7, 1, 3, QtCore.Qt.AlignHCenter)
        self.r_key = QtWidgets.QPushButton(self.widget_2)
        self.r_key.setMinimumSize(QtCore.QSize(35, 35))
        self.r_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.r_key.setFont(font)
        self.r_key.setObjectName("r_key")
        self.gridLayout_2.addWidget(self.r_key, 0, 8, 1, 3)
        self.erase_btn = QtWidgets.QPushButton(self.widget_2)
        self.erase_btn.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.erase_btn.setFont(font)
        self.erase_btn.setStyleSheet("background-color:#4169E1;\n"
"border:none;\n"
"color:#ffffff;\n"
"border-radius:7px;")
        self.erase_btn.setObjectName("erase_btn")
        self.gridLayout_2.addWidget(self.erase_btn, 2, 0, 1, 3)
        self.a_key = QtWidgets.QPushButton(self.widget_2)
        self.a_key.setMinimumSize(QtCore.QSize(35, 35))
        self.a_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.a_key.setFont(font)
        self.a_key.setObjectName("a_key")
        self.gridLayout_2.addWidget(self.a_key, 1, 1, 1, 3, QtCore.Qt.AlignHCenter)
        self.space_btn = QtWidgets.QPushButton(self.widget_2)
        self.space_btn.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.space_btn.setFont(font)
        self.space_btn.setStyleSheet("background-color:#4169E1;\n"
"border:none;\n"
"color:#ffffff;\n"
"border-radius:7px;")
        self.space_btn.setObjectName("space_btn")
        self.gridLayout_2.addWidget(self.space_btn, 1, 0, 1, 1)
        self.u_key = QtWidgets.QPushButton(self.widget_2)
        self.u_key.setMinimumSize(QtCore.QSize(35, 35))
        self.u_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.u_key.setFont(font)
        self.u_key.setObjectName("u_key")
        self.gridLayout_2.addWidget(self.u_key, 0, 15, 1, 2)
        self.q_key = QtWidgets.QPushButton(self.widget_2)
        self.q_key.setMinimumSize(QtCore.QSize(35, 35))
        self.q_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.q_key.setFont(font)
        self.q_key.setObjectName("q_key")
        self.gridLayout_2.addWidget(self.q_key, 0, 0, 1, 2)
        self.g_key = QtWidgets.QPushButton(self.widget_2)
        self.g_key.setMinimumSize(QtCore.QSize(35, 35))
        self.g_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.g_key.setFont(font)
        self.g_key.setObjectName("g_key")
        self.gridLayout_2.addWidget(self.g_key, 1, 13, 1, 2)
        self.Y_key = QtWidgets.QPushButton(self.widget_2)
        self.Y_key.setMinimumSize(QtCore.QSize(35, 35))
        self.Y_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Y_key.setFont(font)
        self.Y_key.setObjectName("Y_key")
        self.gridLayout_2.addWidget(self.Y_key, 0, 13, 1, 2)
        self.p_key = QtWidgets.QPushButton(self.widget_2)
        self.p_key.setMinimumSize(QtCore.QSize(35, 35))
        self.p_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p_key.setFont(font)
        self.p_key.setObjectName("p_key")
        self.gridLayout_2.addWidget(self.p_key, 0, 22, 1, 2)
        self.x_key = QtWidgets.QPushButton(self.widget_2)
        self.x_key.setMinimumSize(QtCore.QSize(35, 35))
        self.x_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.x_key.setFont(font)
        self.x_key.setObjectName("x_key")
        self.gridLayout_2.addWidget(self.x_key, 2, 6, 1, 3, QtCore.Qt.AlignHCenter)
        self.l_ley = QtWidgets.QPushButton(self.widget_2)
        self.l_ley.setMinimumSize(QtCore.QSize(35, 35))
        self.l_ley.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_ley.setFont(font)
        self.l_ley.setObjectName("l_ley")
        self.gridLayout_2.addWidget(self.l_ley, 1, 23, 1, 1)
        self.v_key = QtWidgets.QPushButton(self.widget_2)
        self.v_key.setMinimumSize(QtCore.QSize(35, 35))
        self.v_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.v_key.setFont(font)
        self.v_key.setObjectName("v_key")
        self.gridLayout_2.addWidget(self.v_key, 2, 12, 1, 2)
        self.submit_btn = QtWidgets.QPushButton(self.widget_2)
        self.submit_btn.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submit_btn.setFont(font)
        self.submit_btn.setStyleSheet("background-color:#4169E1;\n"
"border:none;\n"
"color:#ffffff;\n"
"border-radius:7px;")
        self.submit_btn.setObjectName("submit_btn")
        self.gridLayout_2.addWidget(self.submit_btn, 2, 21, 1, 3)
        self.c_key = QtWidgets.QPushButton(self.widget_2)
        self.c_key.setMinimumSize(QtCore.QSize(35, 35))
        self.c_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c_key.setFont(font)
        self.c_key.setObjectName("c_key")
        self.gridLayout_2.addWidget(self.c_key, 2, 9, 1, 3, QtCore.Qt.AlignHCenter)
        self.n_key = QtWidgets.QPushButton(self.widget_2)
        self.n_key.setMinimumSize(QtCore.QSize(35, 35))
        self.n_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.n_key.setFont(font)
        self.n_key.setObjectName("n_key")
        self.gridLayout_2.addWidget(self.n_key, 2, 16, 1, 2)
        self.b_key = QtWidgets.QPushButton(self.widget_2)
        self.b_key.setMinimumSize(QtCore.QSize(35, 35))
        self.b_key.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.b_key.setFont(font)
        self.b_key.setObjectName("b_key")
        self.gridLayout_2.addWidget(self.b_key, 2, 14, 1, 2)
        self.verticalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Date: "))
        self.date_txtlabel.setText(_translate("MainWindow", "12/03/23"))
        self.label_5.setText(_translate("MainWindow", "Time: "))
        self.tim_txtlabel.setText(_translate("MainWindow", "12:02"))
        self.label_10.setText(_translate("MainWindow", "Gender: "))
        self.gender_options.setItemText(0, _translate("MainWindow", "Male"))
        self.gender_options.setItemText(1, _translate("MainWindow", "Female"))
        self.gender_options.setItemText(2, _translate("MainWindow", "Other"))
        self.id_txtlabel.setText(_translate("MainWindow", "Patient ID: 1"))
        self.label_3.setText(_translate("MainWindow", "Weight:"))
        self.weight_txtlael.setText(_translate("MainWindow", "34 kg"))
        self.label_2.setText(_translate("MainWindow", "Name:"))
        self.name_lineEdit.setText(_translate("MainWindow", "hi"))
        self.k_key.setText(_translate("MainWindow", "K"))
        self.t_key.setText(_translate("MainWindow", "T"))
        self.o_key.setText(_translate("MainWindow", "O"))
        self.m_key.setText(_translate("MainWindow", "M"))
        self.j_key.setText(_translate("MainWindow", "J"))
        self.h_key.setText(_translate("MainWindow", "H"))
        self.s_key.setText(_translate("MainWindow", "S"))
        self.f_key.setText(_translate("MainWindow", "F"))
        self.I_key.setText(_translate("MainWindow", "I"))
        self.e_key.setText(_translate("MainWindow", "E"))
        self.w_key.setText(_translate("MainWindow", "W"))
        self.z_key.setText(_translate("MainWindow", "Z"))
        self.d_key.setText(_translate("MainWindow", "D"))
        self.r_key.setText(_translate("MainWindow", "R"))
        self.erase_btn.setText(_translate("MainWindow", "erase"))
        self.a_key.setText(_translate("MainWindow", "A"))
        self.space_btn.setText(_translate("MainWindow", "space"))
        self.u_key.setText(_translate("MainWindow", "U"))
        self.q_key.setText(_translate("MainWindow", "Q"))
        self.g_key.setText(_translate("MainWindow", "G"))
        self.Y_key.setText(_translate("MainWindow", "Y"))
        self.p_key.setText(_translate("MainWindow", "P"))
        self.x_key.setText(_translate("MainWindow", "X"))
        self.l_ley.setText(_translate("MainWindow", "L"))
        self.v_key.setText(_translate("MainWindow", "V"))
        self.submit_btn.setText(_translate("MainWindow", "Submit"))
        self.c_key.setText(_translate("MainWindow", "C"))
        self.n_key.setText(_translate("MainWindow", "N"))
        self.b_key.setText(_translate("MainWindow", "B"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgt= QtWidgets.QMainWindow()
    ui = Edit_patient_details()
    ui.setupUi(wdgt)
    wdgt.show()
    sys.exit(app.exec_())