# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\notification.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Notification_Ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(992, 98)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.notification_container = QtWidgets.QWidget(Form)
        self.notification_container.setMinimumSize(QtCore.QSize(0, 80))
        self.notification_container.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.notification_container.setStyleSheet("color:#ffffff;\n"
"background:#4167e1;\n"
"border-radius:5px;\n"
"position:relative;\n"
"top:0;\n"
"left:0")
        self.notification_container.setObjectName("notification_container")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.notification_container)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.notification_container)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.alarm_icon = QtWidgets.QLabel(self.widget_5)
        self.alarm_icon.setMinimumSize(QtCore.QSize(45, 45))
        self.alarm_icon.setMaximumSize(QtCore.QSize(45, 45))
        self.alarm_icon.setText("")
        self.alarm_icon.setPixmap(QtGui.QPixmap(".\\UI\\../Assets/thermometer-hot (2).png"))
        self.alarm_icon.setScaledContents(True)
        self.alarm_icon.setObjectName("alarm_icon")
        self.horizontalLayout_3.addWidget(self.alarm_icon)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.alarm_text = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.alarm_text.setFont(font)
        self.alarm_text.setScaledContents(True)
        self.alarm_text.setObjectName("alarm_text")
        self.horizontalLayout_3.addWidget(self.alarm_text)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.mute_btn = QtWidgets.QPushButton(self.widget_5)
        self.mute_btn.setMinimumSize(QtCore.QSize(128, 36))
        self.mute_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.mute_btn.setFont(font)
        self.mute_btn.setStyleSheet("background:#ffffff;\n"
"color:#4167e1")
        self.mute_btn.setObjectName("mute_btn")
        self.horizontalLayout_3.addWidget(self.mute_btn)
        self.gridLayout_3.addWidget(self.widget_5, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.notification_container)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.alarm_text.setText(_translate("Form", "Temparature Hot"))
        self.mute_btn.setText(_translate("Form", "Mute for 10s"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
