# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\person_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from domain.domain_patient import Gender, PatientDetail, alarm_log

from edit_patient import Ui_Patient_edit_screen
from patient_detail_card import Ui_patient_detail_card



class Ui_person_history(object):
    def setupUi(self, person_history , patient_details):
        person_history.setObjectName("person_history")
        person_history.resize(840, 614)
        person_history.setStyleSheet("background:#ffffff")
        self.patient_details=patient_details
        self.person_history=person_history
        self.verticalLayout = QtWidgets.QVBoxLayout(person_history)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(person_history)
        self.widget.setMinimumSize(QtCore.QSize(0, 60))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 70))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.clicked.connect(self.addData)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border:1px solid #4169e1;\n"
"border-radius:5px;\n"
"color: #4169e1;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border:1px solid #4169e1;\n"
"border-radius:5px;\n"
"color: #4169e1")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(person_history)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_2)
        self.scrollArea.setStyleSheet("border:none")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 804, 512))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout_2.setSpacing(20)
      

        self.retranslateUi(person_history)
        QtCore.QMetaObject.connectSlotsByName(person_history)


    def addData(self):
        MainWindow = QtWidgets.QDialog(self.person_history)
        ui = Ui_Patient_edit_screen(MainWindow,self.patient_details,self.verticalLayout_2,self.scrollAreaWidgetContents)
        MainWindow.show()
  
    def retranslateUi(self, person_history):
        _translate = QtCore.QCoreApplication.translate
        person_history.setWindowTitle(_translate("person_history", "Form"))
        self.pushButton_2.setText(_translate("person_history", "Add data"))
        self.pushButton.setText(_translate("person_history", "Export as CSV"))
        # self.label_3.setText(_translate("person_history", "Weight: 32kg"))
        # self.label_4.setText(_translate("person_history", "Gender: Male"))
        # self.label_2.setText(_translate("person_history", "Name: Irshit Mukhejee "))
        # self.label_6.setText(_translate("person_history", "Date: 12/02/23"))
        # self.getalarm_logs_btn.setText(_translate("person_history", "Set Current Patient"))
        # self.label_5.setText(_translate("person_history", "Time: 12:20pm"))
        # self.label.setText(_translate("person_history", "Patient Id: 1"))

     





