# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg, NavigationToolbar2QT as NavigationToolbar
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import matplotlib
matplotlib.use('Qt5Agg')


class MplCanvas(FigureCanvasQTAgg):
    def __init__(self, parent=None, width=5, height=4, dpi=100):
        fig = Figure(figsize=(width, height), dpi=dpi)
        self.axes = fig.add_subplot(111)
        super(MplCanvas, self).__init__(fig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 411)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)

        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.update_label)
        self.current_number = 0

        self.capture_timer = QtCore.QTimer()
        self.capture_timer.timeout.connect(self.capture_label_text)

        self.data_log = []

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 20, 621, 391))
        self.stackedWidget.setObjectName("stackedWidget")
        self.logs_page = QtWidgets.QWidget()
        self.logs_page.setObjectName("logs_page")
        self.widget = QtWidgets.QWidget(self.logs_page)
        self.widget.setGeometry(QtCore.QRect(-10, 10, 641, 381))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.back_home_btn = QtWidgets.QPushButton(self.frame_2)
        self.back_home_btn.setObjectName("back_home_btn")
        self.back_home_btn.clicked.connect(self.goto_home_page)
        self.verticalLayout_2.addWidget(self.back_home_btn)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.sc = MplCanvas(self, width=5, height=4, dpi=100)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.stackedWidget.addWidget(self.logs_page)
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.label = QtWidgets.QLabel(self.home_page)
        self.label.setGeometry(QtCore.QRect(310, 120, 55, 71))
        font = QtGui.QFont()
        font.setPointSize(31)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.home_page)
        self.horizontalLayoutWidget.setGeometry(
            QtCore.QRect(120, 220, 401, 131))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.start_btn.setObjectName("start_btn")
        self.start_btn.clicked.connect(self.start_timer)
        self.horizontalLayout.addWidget(self.start_btn)
        self.stop_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stop_btn.setObjectName("stop_btn")
        self.stop_btn.clicked.connect(self.stop_timer)
        self.horizontalLayout.addWidget(self.stop_btn)
        self.stackedWidget.addWidget(self.home_page)
        self.graph_page = QtWidgets.QWidget()
        self.graph_page.setObjectName("graph_page")
        self.gridLayoutWidget = QtWidgets.QWidget(self.graph_page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 591, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.back_home_btn_logs = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.back_home_btn_logs.setObjectName("back_home_btn_logs")
        self.back_home_btn_logs.clicked.connect(self.goto_home_page)
        self.gridLayout_2.addWidget(self.back_home_btn_logs, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2.addWidget(self.frame_3, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.graph_page)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(650, 10, 160, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.side_container = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.side_container.setContentsMargins(0, 0, 0, 0)
        self.side_container.setSpacing(0)
        self.side_container.setObjectName("side_container")
        self.goto_log_details = QtWidgets.QPushButton(
            self.verticalLayoutWidget)
        self.goto_log_details.setIconSize(QtCore.QSize(16, 18))
        self.goto_log_details.setObjectName("goto_log_details")
        self.goto_log_details.clicked.connect(self.goto_logs_page)
        self.side_container.addWidget(self.goto_log_details)
        self.goto_graph = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.goto_graph.setIconSize(QtCore.QSize(16, 16))
        self.goto_graph.setObjectName("goto_graph")
        self.goto_graph.clicked.connect(self.goto_graph_page)
        self.side_container.addWidget(self.goto_graph)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back_home_btn.setText(_translate("MainWindow", "Back To Home"))
        self.label.setText(_translate("MainWindow", "1"))
        self.start_btn.setText(_translate("MainWindow", "start"))
        self.stop_btn.setText(_translate("MainWindow", "stop"))
        self.back_home_btn_logs.setText(_translate("MainWindow", "PushButton"))
        self.goto_log_details.setText(_translate("MainWindow", "Check Log"))
        self.goto_graph.setText(_translate("MainWindow", "Graph"))

    def start_timer(self):
        self.timer.start(200)  # Update label every second
        if self.capture_timer.isActive() == False:
            self.capture_timer.start(5000)
            print('Captured data log', self.data_log)

    def stop_timer(self):
        self.timer.stop()
        self.capture_timer.stop()
        self.data_log.append(self.current_number)

    def update_label(self):
        self.current_number += 1
        if self.current_number > 20:
            self.current_number = 1
        self.label.setText(str(self.current_number))

    def capture_label_text(self):
        self.data_log.append(self.current_number)
        print('Captured data log', self.data_log)

    def goto_logs_page(self):

        self.timer.stop()
        self.capture_timer.stop()

        for number in self.data_log:
            self.label_log = QtWidgets.QLabel()
            self.verticalLayout_2.addWidget(self.label_log)
            self.label_log.setText(str(number))

        self.gridLayout_2.removeWidget(self.sc)

        self.stackedWidget.setCurrentIndex(0)

    def goto_graph_page(self):

        y_axs = self.data_log
        x_axs = [i * 5 for i in range(len(y_axs))]
        self.sc.axes.plot(x_axs, y_axs)
        self.gridLayout_2.addWidget(self.sc)

        # removing log rewrite
        for i in reversed(range(self.verticalLayout_2.count()-1)):
            self.verticalLayout_2.itemAt(i).widget().deleteLater()

        self.stackedWidget.setCurrentIndex(2)

    def goto_home_page(self):
        self.stackedWidget.setCurrentIndex(1)
        self.data_log = []


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
